(function () {
  window.APP_LOCALIZATION = {
    en: {
      brandName: "Arcana Daily",
      languageEnglish: "EN",
      languageVietnamese: "VI",
      historyLink: "Card history",
      refreshLink: "Refresh",
      drawButton: "Draw your card",
      dailyReveal: "Daily reveal",
      revealKicker: "Your card today is",
      continueButton: "Read my reading",
      flipCardButton: "Flip the card",
      shareButton: "Download reading card",
      readingEyebrow: "Arcana Daily",
      coreKeyword: "Core keyword",
      artworkEyebrow: "Artwork speaks through",
      detailedReading: "Detailed reading",
      historyEyebrow: "Daily history",
      historyHeading: "Your recent cards",
      historyEmpty: "Reveal a card to start your reading history.",
      archiveEyebrow: "Archive",
      historyDialogHeading: "Your card history",
      previewEyebrow: "Preview",
      exportHeading: "Your reading card",
      cancel: "Cancel",
      downloadImage: "Download image",
      orientationUpright: "Upright",
      orientationReversed: "Reversed",
      supportKeywords: "Supporting keywords",
      cardHistoryAria: "Card history",
      refreshAria: "Refresh",
      closeAria: "Close",
      themeGeneral: "General",
      themeGeneralIntro: "The tone of the day",
      themeWork: "Work",
      themeWorkIntro: "How this energy wants to move through your work",
      themeRelationship: "Relationship",
      themeRelationshipIntro: "What this card is saying about connection",
      themeMoney: "Money",
      themeMoneyIntro: "How to handle resources and practical choices",
      themeMind: "Mind",
      themeMindIntro: "The inner message beneath the surface"
    },
    vi: {
      brandName: "Arcana Daily",
      languageEnglish: "EN",
      languageVietnamese: "VI",
      historyLink: "Lịch sử lá bài",
      refreshLink: "Làm mới",
      drawButton: "Rút lá bài",
      dailyReveal: "Thông điệp hôm nay",
      revealKicker: "Lá bài hôm nay của bạn là",
      continueButton: "Xem lời giải",
      flipCardButton: "Lật lá bài",
      shareButton: "Tải ảnh lời giải",
      readingEyebrow: "Arcana Daily",
      coreKeyword: "Từ khóa chính",
      artworkEyebrow: "Hình ảnh gợi lên",
      detailedReading: "Lời giải chi tiết",
      historyEyebrow: "Lịch sử hằng ngày",
      historyHeading: "Những lá bài gần đây",
      historyEmpty: "Hãy rút lá bài để bắt đầu lịch sử của bạn.",
      archiveEyebrow: "Lưu trữ",
      historyDialogHeading: "Lịch sử lá bài",
      previewEyebrow: "Xem trước",
      exportHeading: "Ảnh lời giải của bạn",
      cancel: "Hủy",
      downloadImage: "Tải ảnh",
      orientationUpright: "Thuận",
      orientationReversed: "Ngược",
      supportKeywords: "Từ khóa bổ trợ",
      cardHistoryAria: "Lịch sử lá bài",
      refreshAria: "Làm mới",
      closeAria: "Đóng",
      themeGeneral: "Tổng quan",
      themeGeneralIntro: "Năng lượng chung của ngày hôm nay",
      themeWork: "Công việc",
      themeWorkIntro: "Năng lượng này đang đi vào công việc của bạn như thế nào",
      themeRelationship: "Tình cảm",
      themeRelationshipIntro: "Lá bài này đang nói gì về sự kết nối",
      themeMoney: "Tài chính",
      themeMoneyIntro: "Cách xử lý tiền bạc và những lựa chọn thực tế",
      themeMind: "Tâm trí",
      themeMindIntro: "Thông điệp bên trong đang muốn được nhìn thấy"
    }
  };
})();
